### ISSUE TITLE
'charmap' codec can't decode byte

### ISSUE THREAD

**Issue by matej2** [openschemas/schemaorg#37]
**Describe the bug**

I tried one of the examples: require-all (https://github.com/openschemas/schemaorg/tree/master/examples/require-all). When I run the example, it returns me the following error:

```
Specification base set to https://www.schema.org
Using Version 12.0
Traceback (most recent call last):
  File "<user_dir><project_dir>\schemaorg-model-generator\main.py", line 6, in <module>
    schema = Schema('SportsEvent')
  File "<user_dir>.virtualenvs\schemaorg-model-generator-poHh6h-y\lib\site-packages\schemaorg\main\__init__.py", line 35, in __init__
    self.load_type(schema_type)
  File "<user_dir>.virtualenvs\schemaorg-model-generator-poHh6h-y\lib\site-packages\schemaorg\main\__init__.py", line 174, in load_type
    self._load_type(schema_type)
  File "<user_dir>.virtualenvs\schemaorg-model-generator-poHh6h-y\lib\site-packages\schemaorg\main\__init__.py", line 277, in _load_type
    typs = read_types_csv(version = self.version)
  File "<user_dir>.virtualenvs\schemaorg-model-generator-poHh6h-y\lib\site-packages\schemaorg\data\__init__.py", line 91, in read_types_csv
    return read_csv(filename, keyfield=keyfield)
  File "<user_dir>.virtualenvs\schemaorg-model-generator-poHh6h-y\lib\site-packages\schemaorg\utils.py", line 289, in read_csv
    for row in csv_reader:
  File "c:\program files\python39\lib\csv.py", line 111, in __next__
    row = next(self.reader)
  File "c:\program files\python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6377: character maps to <undefined>
```

**To Reproduce**

1. Create empty recipe yml as described
2. Code:
```
from schemaorg.main import Schema
from schemaorg.utils import read_yaml, write_yaml


recipe = read_yaml('empty.yml')
schema = Schema('SportsEvent')
```

**Expected behavior**
I would get schema back.

**Version of Python schemaorg**
0.1.0

Anything else?
I hope this helps. I hope I provided enough info, ask if you need anything.

**Comment by vsoch** [comment]
It looks like you are on Windows and there is an encoding that isn't recognized. Could you please try seeing if you can tweak this function: https://github.com/openschemas/schemaorg/blob/6afa9194c0c08b0ab2c0692d4d1863ee8711ccc0/schemaorg/utils.py#L287 to catch the exception, and then try reading with another codec? There is an example of how to do that here: https://stackoverflow.com/questions/30598350/unicodedecodeerror-charmap-codec-cant-decode-byte-0x8d-in-position-7240-cha

**Comment by matej2** [comment]
Ok, I tried it and managed to get rid of the error. I will open a PR for this.

**Comment by matej2** [comment]
The issue is fixed now. Thanks

**Comment by vsoch** [comment]
https://pypi.org/project/schemaorg/0.1.1/
